#!/bin/bash
# /Users/davidhsieh/.config/yabai/mpv_opacity
# Sourced from https://github.com/koekeishiya/yabai/issues/503#issuecomment-651786100 and edited for mpv

MPV_PID=$(yabai -m query --windows | jq -r '.[] | select(.app == "mpv").pid' | uniq)
MPV_ID=$(yabai -m query --windows | jq -r '.[] | select((.app == "mpv") and (.topmost == 1)).id' | uniq)

if [ -z "$MPV_PID" ] || [ -z "$MPV_ID" ]; then
  # mpv isn't open or isn't topmost
  exit 0
fi

if ! yabai -m query --windows \
    | jq -er "map(select((.pid == $MPV_PID) and (.focused == 1))) | length >= 1" >  /dev/null
then
  # mpv hasn't any focused windows
  # Set opacity to 0.6
  yabai -m window $MPV_ID --opacity 1.0
  exit 0
fi

# mpv is focused, fallback to default opacity settings
yabai -m window $MPV_ID --opacity 0.0
exit 0
